### ISSUE TITLE
Consider merging into nevermore "classic" ?

### ISSUE THREAD

**Issue by eLvErDe** [brian112358/nevermore-miner-x16s#2]
Hi,

I see it's a quick n dirty port but do you consider merging x16r and x16s together in a single app ?

Regards, Adam.

**Comment by BobbyGR** [comment]
I agree.  Aiominer has nevermore. But I won't add this as it's another download for no reason other than 1 algo

**Comment by brian112358** [comment]
Finally done! The [latest release of Nevermore](https://github.com/brian112358/nevermore-miner/releases) has x16s support. I'm deprecating this repository and moving over to the main Nevermore repository for further work on x16s.
